### ISSUE TITLE
System.IO.IOException: The process cannot access the file '/app/cEo2K3x6KtU.live_chat.json' because it is being used by another process.

### ISSUE THREAD

**Issue by jim60105** [jim60105/YoutubeLiveChatToDiscord#6]
Master Branch沒改code，docker image重build後出問題
![image](https://user-images.githubusercontent.com/16995691/165525018-3c16a538-7c0c-451a-9bae-962c764bf73b.png)

目前已知正常的最後image是`ghcr.io/jim60105/youtubelivechattodiscord@sha256:dbdcac40e1acfd5b036c93152dd5d85579bb380c8667b770c133520ee382a247`
在問題修復前請docker pull這一版

**Comment by jim60105** [comment]
After testing, this issue #6 does not exist with yt-dlp v2022.2.4, but it is wrong in v2022.3.8.

I think it's related to this issue https://github.com/yt-dlp/yt-dlp/issues/3124
But I am executing in Linux Container, not Windows environment. This does not match the discussion in the issue, it may be other problem.
The fix [here](https://github.com/sulyi/yt-dlp/commit/89cc910e9fe863e1c56f1eae1678821597645fd5) for the issue seems to be only for the win32 environment, so won't fix the problem I encountered.

Finally,
I decided to hard code the version number to v2022.2.4 in DockerFile as a workaround.
https://github.com/jim60105/YoutubeLiveChatToDiscord/blob/6304300ef32ce9b6eb10688f22d46962c8afb804/Dockerfile#L7

**Comment by jim60105** [comment]
yt-dlp v2022.2.4 is no longer working.
This issue still exists on the latest version of yt-dlp.

**Comment by jim60105** [comment]
```
2023-02-20 18:04:23 fail: Microsoft.Extensions.Hosting.Internal.Host[9]
2023-02-20 18:04:23       BackgroundService failed
2023-02-20 18:04:23       System.IO.IOException: The process cannot access the file '/app/GDEinoJcTRk.live_chat.json' because it is being used by another process.
2023-02-20 18:04:23          at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
2023-02-20 18:04:23          at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
2023-02-20 18:04:23          at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
2023-02-20 18:04:23          at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
2023-02-20 18:04:23          at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
2023-02-20 18:04:23          at YoutubeLiveChatToDiscord.LiveChatMonitorWorker.ProcessChats(CancellationToken stoppingToken) in E:\repos\LiveChatToDiscord\LiveChatMonitorWorker.cs:line 151
2023-02-20 18:04:23          at YoutubeLiveChatToDiscord.LiveChatMonitorWorker.Monitoring(CancellationToken stoppingToken) in E:\repos\LiveChatToDiscord\LiveChatMonitorWorker.cs:line 105
2023-02-20 18:04:23          at YoutubeLiveChatToDiscord.LiveChatMonitorWorker.ExecuteAsync(CancellationToken stoppingToken) in E:\repos\LiveChatToDiscord\LiveChatMonitorWorker.cs:line 59
2023-02-20 18:04:23          at YoutubeLiveChatToDiscord.LiveChatMonitorWorker.ExecuteAsync(CancellationToken stoppingToken) in E:\repos\LiveChatToDiscord\LiveChatMonitorWorker.cs:line 74
2023-02-20 18:04:23          at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
2023-02-20 18:04:23 crit: Microsoft.Extensions.Hosting.Internal.Host[10]
2023-02-20 18:04:23       The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
2023-02-20 18:04:23       System.IO.IOException: The process cannot access the file '/app/GDEinoJcTRk.live_chat.json' because it is being used by another process.
2023-02-20 18:04:23          at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
2023-02-20 18:04:23          at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
2023-02-20 18:04:23          at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
2023-02-20 18:04:23          at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
2023-02-20 18:04:23          at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
2023-02-20 18:04:23          at YoutubeLiveChatToDiscord.LiveChatMonitorWorker.ProcessChats(CancellationToken stoppingToken) in E:\repos\LiveChatToDiscord\LiveChatMonitorWorker.cs:line 151
2023-02-20 18:04:23          at YoutubeLiveChatToDiscord.LiveChatMonitorWorker.Monitoring(CancellationToken stoppingToken) in E:\repos\LiveChatToDiscord\LiveChatMonitorWorker.cs:line 105
2023-02-20 18:04:23          at YoutubeLiveChatToDiscord.LiveChatMonitorWorker.ExecuteAsync(CancellationToken stoppingToken) in E:\repos\LiveChatToDiscord\LiveChatMonitorWorker.cs:line 59
2023-02-20 18:04:23          at YoutubeLiveChatToDiscord.LiveChatMonitorWorker.ExecuteAsync(CancellationToken stoppingToken) in E:\repos\LiveChatToDiscord\LiveChatMonitorWorker.cs:line 74
2023-02-20 18:04:23          at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
```

**Comment by jim60105** [comment]
yt-dlp locks this file in Linux, but not in Windows.
Implementation: https://github.com/yt-dlp/yt-dlp/commit/897376719871279eef89426b1452abb89051f0dc
Issue: https://github.com/yt-dlp/yt-dlp/issues/3124

Unlike Windows, which has an exclusive lock, Linux has an advisory lock, so the program can decide whether to comply with the lock or not.
FileStream "will" comply with the lock, so it will report an error when opening a file here.
For more details, please refer to this issue, where the discussion process is explained very clearly: `https://github.com/dotnet/runtime/issues/34126`
This is the description of the locking design for .NET Core on Linux and Windows: `https://github.com/dotnet/runtime/pull/55256`
NET 6 onwards, you can add the environment variable "DOTNET_SYSTEM_IO_DISABLEFILELOCKING" to make FileStream "not" comply with locking.

This project will add this environment variable to the Dockerfile.
